version: '3'
services:
  frontend:
    image: gangster569/frontend-image:latest
    ports:
      - "3000:3000"
    environment:
      REACT_APP_CLOUDINARY_CLOUD_NAME: dpc7fwkte
      REACT_APP_BACKEND_URL: http://localhost:8081  
      
    networks:
      - app-network

  backend:
    image: gangster569/backend-image:latest
    ports:
      - "8081:8081"
    environment:
      MONGODB_URI: mongodb+srv://kadavakollagowthamreddy:gowthamreddy@chat-app.st4mb.mongodb.net/?retryWrites=true&w=majority&appName=chat-app
      JWT_SECRET_KEY: jhdcjhsdvchjsdhbfasdgbvs
      FRONTEND_URL: http://localhost:3000
      PORT: 8081
    # deploy:
    #   resources:
    #     limits:
    #       memory: 512M
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
