---
- name: Deploy MERN Application
  hosts: all
  become: false
  vars:
    ansible_become_pass: "9960"

  tasks:
    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: "{{ playbook_dir }}/docker-compose.yml"
    - name: debug
      debug:
        
    - name: Run Docker Compose
      command: docker-compose up -d