apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: mern-app
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gangster569/backend-image:latest
          # resources:
          #   limits:
          #     memory: "4Gi"
          #     # cpu: "500m"
          ports:
            - name: http
              containerPort: 8081
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mern-backend-secret
                  key: MONGODB_URI
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mern-backend-secret
                  key: JWT_SECRET_KEY
            - name: FRONTEND_URL
              valueFrom:
                secretKeyRef:
                  name: mern-backend-secret
                  key: FRONTEND_URL
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: mern-backend-secret
                  key: PORT
