apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: mern-app
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      # NodePort: 3000
  type: NodePort
