apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: mern-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gangster569/frontend-image:latest
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: mern-frontend-secret
                  key: REACT_APP_CLOUDINARY_CLOUD_NAME
            - name: REACT_APP_BACKEND_URL
              valueFrom:
                secretKeyRef:
                  name: mern-frontend-secret
                  key: REACT_APP_BACKEND_URL
            - name: REACT_APP_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-configmap
                  key: REACT_APP_BASE_URL
